# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Where the hell are you?
description: > # this means to ignore newlines until "baseurl:"
  Just me deep in here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site

#facebook: zpedro6

# Build settings
markdown: kramdown
theme: minima

# User settings
username: José Pedro Duarte
user_description: Sort of a Programmer.
user_title: Lorem Ipsum
email: josepduarte66@gmail.com
facebook_username: zpedro6
gplus_username:  100113997000058098899
github_username: josepduarte
